#!/usr/bin/env bash
#
################################
#      _                       #
#  ___| |_ _ __ __ _ ______ _  #
# / __| __| '__/ _` |_  / _` | #
# \__ \ |_| | | (_| |/ / (_| | #
# |___/\__|_|  \__,_/___\__,_| #
#                              #
#------------------------------#
#  Instalador de dependencias  #
#       para Arch Linux	       #
################################

read PROGRAMAS
sudo pacman -S --noconfirm $PROGRAMAS

